[package]
name = "ds_std"
version = "0.0.0"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }

[addresses]
ds_std = "0x555"
std =  "0x1"
